- src/components/keyValue/keyValue.component.ts
Change KeyValue component to be used when we need to retrieve the array of keyValue everytime we acess the component
> Add model condition when populate KeyValues

- src/components/index.ts
- src/components/viewMoreBar/ViewMoreBar.scss
- src/components/viewMoreBar/viewMoreBar.component.ts
Added view more bar to encapsulate a load more bar behavior. This was made because of problems with the infinite-scroll directive. The corresponding file is here https://www.figma.com/file/Du6TFhrzzRjJaJJNKa7tTu/aprimoramento_ai_ajuste-rapido?node-id=1%3A94
> View more bar

- src/components/avatar/AvatarView.html
Fix a misplaced reference in avatar tooltip
> fix(client): fix avatar tooltip

- src/components/avatar/Avatar.scss
> fix(component): fix component size

- src/components/blipTable/blipTable.component.ts
Trying to generate new release
> feat(client): releasing new blip-table

- package.json
- src/components/blipTable/blipTable.component.ts
feature/147507-enhancement-table-component
Removing beta from package.json version in hopes to generate a new release
> fix(client): removing beta from package.json version

- package.json
- src/components/blipInputDpr/blipInputDprView.html
feature/147935-appearance_changes
> fix(component): color label in red if input invalid. #150090

- src/components/switch/SwitchController.js
- src/components/switch/index.js
feature/add-ngDisable-to-switch
> feat(client): adding ngDisable to switch

- src/components/switch/SwitchController.js
- src/components/switch/SwitchView.html
- src/components/switch/index.js
- src/components/switch/switch.scss
feature/add-ngDisable-to-switch
> feat(client): using disabled instead ngDisabled

- src/components/sortingArrows/sortingArrows.component.ts
- src/components/sortingArrows/sortingArrows.scss
> fix(component): fix the disable binding on sortingArrows component

- src/assets/scss/variables.scss
- src/components/switch/switch.scss
feature/add-ngDisable-to-switch
> fix(client): changing colors of switch

- src/components/confusionMatrix/ConfusionMatrix.scss
- src/components/confusionMatrix/ConfusionMatrixView.html
- src/components/confusionMatrix/confusionMatrix.component.ts
On component confusion matrix:
- adding color to cells according to the result occurrence;
- adding color to the main diagonal;
- changing color of selected column and row;
- changing color of the cell on hover.
> fix(client): adding color to CM  main diagonal

- package.json
> feat(client): update toolkit

- src/components/blipSelect/blipSelect.component.ts
feature/158104-add-multiple-to-blip-selected
> feat(client): adding multiple seletion behaviour to blip-select

- src/components/impactCircle/ImpactCircleView.html
- src/components/impactCircle/impactCircle.component.ts
Change the static description of Inpact Circle for a data binding description on the component. Change made because of the reafactor on BlipPortal tranlations.
feature/159400_add_description_data_binding_to_impact_circle
> fix(component): add description data-binding to impact circle

- package.json
> feat(client): update packages

- src/components/dropdownItem/DropdownItemController.ts
- src/components/dropdownItem/index.ts
> feat(component): add on close binding

- src/components/blipLoading/blipLoading.component.ts
- src/components/index.ts
creating blipLoading component
> feat(component): creating blipLoading component

- src/components/expandableList/expandableItem/index.ts
> feat(component): add isActive binding to tell if item is active

- src/components/contentBoxes/ContentBoxesController.js
- src/components/contentBoxes/ContentBoxesView.html
- src/components/contentBoxes/index.js
Adding a disable condition to the save button on Content Box component, also removing the
translations.
> feat(component): add disable to save button on content box

- src/components/icon/icon.component.ts
Fix <icon> component svg color on microsoft edge.
feature/164507_icon_color_fix
> fix(component): fixing icon color on microsoft edge

- package.json
- src/components/blipSelect/blipSelect.component.ts
feature/166765-add-disabled-option-click-callback
> feat(client): adding disabled option click callback

- src/components/tooltipButton/tooltipButton.component.ts
> fix(component): add possibility to use icon component in tooltip button

- src/components/threadMessages/threadMessages.component.ts
included timeout cleaning in threadMessages component to avoid memory leaks
bugfix/168308-memory-leaks-improvements
> fix(component): included timeout cleaning in ThreadMessages component

- package.json
bugfix/183897-fixing-date-picker
> fix(component): updating blip-toolkit

- src/components/blipDaterangePicker/blipDaterangePicker.component.ts
bugfix/fixing_blipDaterangePicker_translation
> fix(client): using translate on blipDaterangePicker

- src/components/blipDaterangePicker/blipDaterangePicker.component.ts
feature/189156-fixing-daterangePicker-days
> fix(client): fixing daterange picker days translation

- package.json
- src/directives/autoExpand/AutoExpand.Directive.ts
- src/modules/index.ts
add sanitization to prevent html injection
> feat(component): add sanitization on auto-expand directive

- src/components/keyValue/keyValue.component.ts
Insert for adjust for production
183164_Redo-Undo_Actions_Define_Variables_and_others
> feat(component): adjust for build prod

- src/components/keyValue/KeyValueView.html
bugfix/prevent-key-value-add-submit
> fix(component): prevent key value add button to submit forms

- package.json
Upgrading toolkit to fix daterange time selection
ISSUES CLOSED: #196561
bugfix/196561-fixing-time-selection-updating-toolkit
> fix(component): upgrading toolkit to fix daterange time selection

- package.json
Upgrading toolkit in order to fix month exibition when period is selected
ISSUES CLOSED: #199960
> fix(component): upgrading toolkit to fix month exibition

- package.json
Upgrading toolkit and adding space to build work
ISSUES CLOSED: #199960
> fix(component): upgrading toolkit and adding space to build work

- package.json
- src/directives/inputSanitize/inputSanitize.directive.ts
> feat(component): change input sanitize library

- src/directives/inputSanitize/inputSanitize.directive.ts
bugfix/199677_ssml_sanitize_attributes
> feat(component): set allowed attributes to input sanitize

- package.json
- src/directives/inputSanitize/inputSanitize.directive.ts
feature/199677_sanitize_html_module
> feat(component): add sanitize html type declaration

- src/components/sortingArrows/sortingArrows.scss
> feat(configs): remove test

- src/components/card/card.scss
Setting card border radius to 8px to be updated with the last card design definition
ISSUES CLOSED: 203006
> feat(component): updating card border radius

- src/components/contentTabs/index.ts
- src/components/contentTabs/tab/index.ts
bugfix/201085-render-on-only-one-sidebar, Fixing sidebar closing opened views.
> fix(client): rendering on one sidebar

- src/components/dropdownItem/DropdownItemController.ts
add window event listeners to dropdown component
> Fix dropdown closing when clicking on iframe

- src/components/contentTabs/contentTabs.scss
> fix(client): centralize content tab items

- src/components/contentTabs/contentTabs.scss
> fix(client): return to old behavior

- package.json
Reverting type node to 14.14.20
> feat(headstart): reverting types for 14.14.20

- package.json
A fix was implemented in blip tookit and we need to update blip components to use the new version on blip portal.
> fix(build): update package.json

- src/components/subheaderIcons/SubheaderIconsView.html
- src/components/subheaderIcons/SubheaderIconsView.scss
fix(subheader): add tooltip on test icon when testing unpublished bot
> fix(subheader): add tooltip on test icon when testing unpublished bot

- src/components/subheaderIcons/SubheaderIconsView.html
- src/components/subheaderIcons/SubheaderIconsView.scss
Add supports to the "fullscreen" class to Builder so components will behave correctly when in fullscreen.
> #203061 feat: adds CSS to respond to builder in fullscreen

- README.md
- package.json
- src/components/dropdownItem/DropdownItemController.ts
- src/components/dropdownItem/DropdownItemView.html
- src/components/dropdownItem/index.ts
Change the component icon dropdownItem and update the angular-sanitize library
> fix: changed the icon components dropdown

- src/components/blipDaterangePicker/blipDaterangePicker.component.ts
Change component to fix  bug on blip portal afeter updated libs
> fix(Daterangepicker): fix-bug-selecting-period

- src/components/blipTags/blipTags.component.ts
BlipTags component fixes due to Angular update (1.5 -> 1.8)
> Fix: bug of creating an instance of BlipTags

- src/components/threadMessages/ThreadMessagesView.html
- src/components/threadMessages/threadMessages.component.ts
Create a new event to fire when the scroll hits the bottom and changing ticket id to the message id, whether it is a ticket or not, so that it can be located through the html (message.document.id is same as ticket (id))
> feat(threadMessages): adding call event on bottom
